[package]
name = "symdex-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "symdex"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
serde_json = "1.0.149"
symdex-core = { path = "../symdex-core" }
symdex-embed = { path = "../symdex-embed" }
symdex-mcp = { path = "../symdex-mcp" }
symdex-store = { path = "../symdex-store" }
